name: Package App to IPA

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  package-ipa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Package Payload and Zip to IPA
        run: |
          mkdir Payload
          cp -r filetransfer.app Payload/
          zip -r FileTransfer.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FileTransfer-IPA
          path: FileTransfer.ipa
